export const MENU = [
  {
    id: 1,
    firstCategory: "중식",
    secondCategory: "밥",
    thirdCategory: "국물 O",
    description: "마라탕",
    imgURL: "../src/asset/Chinese/rice/rice1.jpeg",
  },
  {
    id: 2,
    firstCategory: "중식",
    secondCategory: "밥",
    thirdCategory: "국물 X",
    description: "마파두부 밥",
    imgURL: "../src/asset/Chinese/rice/rice2.jpeg",
  },
  {
    id: 3,
    firstCategory: "중식",
    secondCategory: "면",
    thirdCategory: "국물 X",
    description: "마라샹궈",
    imgURL: "../src/asset/Chinese/noodle/noodle1.jpeg",
  },
  {
    id: 4,
    firstCategory: "중식",
    secondCategory: "면",
    thirdCategory: "국물 O",
    description: "우육면",
    imgURL: "../src/asset/Chinese/noodle/noodle2.jpeg",
  },
  {
    id: 5,
    firstCategory: "중식",
    secondCategory: "고기/해물",
    thirdCategory: "국물 X",
    description: "꿔바로우",
    imgURL: "../src/asset/Chinese/etc/etc1.jpeg",
  },
  {
    id: 6,
    firstCategory: "중식",
    secondCategory: "고기/해물",
    thirdCategory: "국물 O",
    description: "칠리새우",
    imgURL: "../src/asset/Chinese/etc/etc2.jpeg",
  },
  {
    id: 7,
    firstCategory: "중식",
    secondCategory: "고기/해물",
    thirdCategory: "국물 O",
    description: "크림새우",
    imgURL: "../src/asset/Chinese/etc/etc3.jpeg",
  },
  {
    id: 8,
    firstCategory: "일식",
    secondCategory: "밥",
    thirdCategory: "국물 X",
    description: "장어 덮밥",
    imgURL: "../src/asset/Japanese/rice/rice1.jpeg",
  },
  {
    id: 9,
    firstCategory: "일식",
    secondCategory: "밥",
    thirdCategory: "국물 X",
    description: "초밥",
    imgURL: "../src/asset/Japanese/rice/rice2.jpeg",
  },
  {
    id: 10,
    firstCategory: "일식",
    secondCategory: "밥",
    thirdCategory: "국물 O",
    description: "스키야키",
    imgURL: "../src/asset/Japanese/rice/rice3.jpeg",
  },
  {
    id: 11,
    firstCategory: "일식",
    secondCategory: "면",
    thirdCategory: "국물 O",
    description: "라멘",
    imgURL: "../src/asset/Japanese/noodle/noodle1.jpeg",
  },
  {
    id: 12,
    firstCategory: "일식",
    secondCategory: "면",
    thirdCategory: "국물 X",
    description: "마제소바",
    imgURL: "../src/asset/Japanese/noodle/noodle2.webp",
  },
  {
    id: 13,
    firstCategory: "일식",
    secondCategory: "고기/해물",
    thirdCategory: "국물 X",
    description: "타코야키",
    imgURL: "../src/asset/Japanese/etc/etc1.jpeg",
  },
  {
    id: 14,
    firstCategory: "일식",
    secondCategory: "고기/해물",
    thirdCategory: "국물 O",
    description: "규카츠",
    imgURL: "../src/asset/Japanese/etc/etc2.jpeg",
  },
  {
    id: 15,
    firstCategory: "한식",
    secondCategory: "밥",
    thirdCategory: "국물 O",
    description: "김치찌개",
    imgURL: "../src/asset/Korean/rice/rice1.jpeg",
  },
  {
    id: 16,
    firstCategory: "한식",
    secondCategory: "밥",
    thirdCategory: "국물 O",
    description: "부대찌개",
    imgURL: "../src/asset/Korean/rice/rice2.jpeg",
  },
  {
    id: 17,
    firstCategory: "한식",
    secondCategory: "밥",
    thirdCategory: "국물 X",
    description: "비빔밥",
    imgURL: "../src/asset/Korean/rice/rice3.avif",
  },
  {
    id: 18,
    firstCategory: "한식",
    secondCategory: "면",
    thirdCategory: "국물 O",
    description: "냉면",
    imgURL: "../src/asset/Korean/noodle/noodle1.jpeg",
  },
  {
    id: 19,
    firstCategory: "한식",
    secondCategory: "면",
    thirdCategory: "국물 X",
    description: "비빔국수",
    imgURL: "../src/asset/Korean/noodle/noodle2.jpeg",
  },
  {
    id: 20,
    firstCategory: "한식",
    secondCategory: "면",
    thirdCategory: "국물 O",
    description: "잔치국수",
    imgURL: "../src/asset/Korean/noodle/noodle3.jpeg",
  },
  {
    id: 21,
    firstCategory: "한식",
    secondCategory: "고기/해물",
    thirdCategory: "국물 O",
    description: "간장게장",
    imgURL: "../src/asset/Korean/etc/etc1.jpeg",
  },
  {
    id: 22,
    firstCategory: "한식",
    secondCategory: "고기/해물",
    thirdCategory: "국물 X",
    description: "삼겹살",
    imgURL: "../src/asset/Korean/etc/etc2.jpeg",
  },
];
